name: pyBenD CI 
on: pull_request

# Cancels in-progress workflows for a PR when updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: mpi4py/setup-mpi@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.2
        cache: 'pip'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install the code linting and formatting tool Ruff
      run: pipx install ruff
    - name: Lint code with Ruff
      run: ruff check --fix --output-format=github --target-version=py312
    - name: Check code formatting with Ruff
      run: ruff format --diff --target-version=py312
      continue-on-error: true
    - name: Typing check with mypy
      run:  |
        pipx install mypy
        mypy --namespace-packages --explicit-package-bases --disallow-subclassing-any --ignore-missing-import
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install yapf toml
        python -m pip install ./
